# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    target-branch: 'next'
    schedule:
      interval: 'daily'
    groups:
      react:
        patterns:
          - 'react*'
      typescript:
        patterns:
          - '@types*'
          - 'ts*'
          - 'typescript*'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint*'
      radix:
        patterns:
          - '@radix-ui*'
      vite|vitest:
        patterns:
          - 'vite*'
          - '@vite*'
      tailwind:
        patterns:
          - 'tailwind*'
          - '@tailwind*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
